using System;
using System.Collections.Generic;

namespace RetailOps.Domain.Entities;

public partial class Actions
{
    public string Id { get; set; } = null!;

    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    public string? Status { get; set; }

    public string? Priority { get; set; }

    public string? Type { get; set; }

    public string? CreatedBy { get; set; }

    public string? AssignedTo { get; set; }

    public string? SellerId { get; set; }

    public string? GoalId { get; set; }

    public string? ObjectiveId { get; set; }

    public string? KeyResultId { get; set; }

    public DateTime? DueDate { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string? Source { get; set; }

    public string? SourceId { get; set; }

    public string? AsinId { get; set; }

    public bool? IsAIGenerated { get; set; }

    public string? AiReasoning { get; set; }

    public string? ResolvedAsins { get; set; }

    public string? AutoGeneratedSource { get; set; }

    public string? Asins { get; set; }

    public string? Stage { get; set; }

    public string? TimeTracking { get; set; }

    public string? Submission { get; set; }

    public string? Rejections { get; set; }

    public string? ReviewDecision { get; set; }

    public string? Category { get; set; }

    public int? TimeLimit { get; set; }

    public string? SubTasks { get; set; }

    public string? SubTaskProgress { get; set; }

    public virtual ICollection<ActionHistory> ActionHistory { get; set; } = new List<ActionHistory>();

    public virtual Users? AssignedToNavigation { get; set; }

    public virtual Users? CreatedByNavigation { get; set; }

    public virtual Goals? Goal { get; set; }

    public virtual KeyResults? KeyResult { get; set; }

    public virtual Objectives? Objective { get; set; }

    public virtual Sellers? Seller { get; set; }
}
